#!/usr/bin/env python3
"""Builds the App Design tab that lives inside Roadmap -> System Design.

Same SECTIONS as build_appdesign.py, so the standalone page and the roadmap tab
can never drift. Emits two files:

    js/content-appdesign.js   the tab, spliced into SYSDES_CONTENT after Patterns
    css/appdesign-topic.css   the book's own CSS, scoped to .ad-book

    python3 build_roadmap_tab.py
"""

import json
import os
import re

import build_appdesign as book

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE_DIR)
JS_OUT = os.path.join(ROOT, "js", "content-appdesign.js")
CSS_OUT = os.path.join(ROOT, "css", "appdesign-topic.css")

# Page chrome that has no meaning inside a roadmap topic.
DROP = re.compile(
    r"^(?:\*|html|body|\.layout|\.sidebar|\.toc|\.nav-toggle|\.content"
    r"|h1\.page-title|h2\.sec|\.page-sub)\b"
)
# From `body`, keep only what should cascade into the topic body.
BODY_KEEP = ("font-family", "line-height")


def scope_css(css: str, scope: str = ".ad-book") -> str:
    """Prefix every kept rule with `scope` so the book styles cannot leak."""
    out = []
    # Pull @media blocks out first; the rest is a flat list of rules.
    media_blocks = []

    def stash(m):
        media_blocks.append(m.group(0))
        return f"\x00MEDIA{len(media_blocks) - 1}\x00"

    css = re.sub(r"@media[^{]+\{(?:[^{}]|\{[^{}]*\})*\}", stash, css)

    def rules(block: str) -> str:
        kept = []
        for m in re.finditer(r"([^{}]+)\{([^{}]*)\}", block):
            sels, body = m.group(1).strip(), m.group(2).strip()
            if not sels or sels.startswith("\x00"):
                continue
            parts = [p.strip() for p in sels.split(",") if p.strip()]
            new_parts = []
            for p in parts:
                if p == ":root":
                    # :root is <html>, never a descendant of the scope - the
                    # custom properties have to land on the wrapper itself.
                    kept.append("%s { %s }" % (scope, body))
                    continue
                if p == "body":
                    decls = "; ".join(
                        d.strip() for d in body.split(";")
                        if d.strip() and d.split(":")[0].strip() in BODY_KEEP
                    )
                    if decls:
                        kept.append(f"{scope} {{ {decls}; }}")
                    continue
                if DROP.match(p):
                    continue
                new_parts.append(p if p.startswith(scope) else f"{scope} {p}")
            if new_parts and body:
                kept.append("%s { %s }" % (", ".join(new_parts), body))
        return "\n".join(kept)

    out.append(rules(css))
    for block in media_blocks:
        cond = block[: block.index("{")].strip()
        inner = block[block.index("{") + 1 : block.rindex("}")]
        scoped = rules(inner)
        if scoped.strip():
            out.append("%s {\n%s\n}" % (cond, scoped))
    return "\n".join(x for x in out if x.strip())


def build() -> None:
    sections = book.SECTIONS

    topics = []
    for number, (sid, title, content) in enumerate(sections, start=1):
        # The standalone page numbers its sections; keep that so cross-references
        # in the prose ("see section 5") still line up.
        learn = (
            f'<div class="ad-book" id="ad-{sid}">'
            f'<div class="ad-secnum">Section {number} of {len(sections)}</div>'
            f"{content}"
            "</div>"
        )
        topics.append({"t": f"{number}. {title}", "learn": learn})

    tab = {"id": "appdesign", "t": "App Design", "topics": topics}

    js = (
        "// ============================================================\n"
        "// App Architecture & Data Modeling - Roadmap tab\n"
        "//\n"
        "// GENERATED by appdesign/build_roadmap_tab.py - do not edit by hand.\n"
        "// Same sections as appdesign/appdesign_prep.html, so the standalone\n"
        "// page and this tab stay in step. Re-run the script after editing any\n"
        "// appdesign/sections_*.py file.\n"
        "// ============================================================\n\n"
        "const APPDESIGN_TAB = " + json.dumps(tab, indent=1, ensure_ascii=False) + ";\n\n"
        "// Slot it into System Design, immediately after Patterns & Case Studies.\n"
        "if (typeof SYSDES_CONTENT !== 'undefined' && SYSDES_CONTENT.tabs) {\n"
        "  const at = SYSDES_CONTENT.tabs.findIndex(t => t.id === 'patterns');\n"
        "  SYSDES_CONTENT.tabs.splice(at < 0 ? SYSDES_CONTENT.tabs.length : at + 1, 0, APPDESIGN_TAB);\n"
        "}\n"
    )
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(js)

    css = (
        "/* GENERATED by appdesign/build_roadmap_tab.py - do not edit by hand.\n"
        "   The standalone book's stylesheet, scoped to .ad-book so it styles the\n"
        "   App Design topics inside the roadmap without touching anything else. */\n\n"
        + scope_css(book.CSS)
        + "\n\n/* roadmap-only chrome */\n"
        ".ad-book { color: #e6e6e6; }\n"
        # Code blocks follow the app's own .learn-code / inline-code styling, so an
        # App Design topic does not read as a different product to the topic above it.
        ".ad-book pre { background:#1e1e1e; border:1px solid #2a2a2a; border-radius:3px;\n"
        "  padding:10px 12px; font-size:13px; line-height:1.6; color:#d4d4d4;\n"
        "  margin:8px 0 12px; max-height:300px; overflow:auto; white-space:pre; }\n"
        ".ad-book code { background:#1a1a1a; border:1px solid #2a2a2a; border-radius:3px;\n"
        "  padding:1px 5px; font-size:13px; color:#ce9178; }\n"
        ".ad-book pre code { background:none; border:none; padding:0;\n"
        "  font-size:inherit; color:inherit; }\n"
        ".ad-book .ad-secnum { font-family: system-ui, -apple-system, sans-serif;\n"
        "  font-size: .68rem; letter-spacing: .09em; text-transform: uppercase;\n"
        "  color: #9aa0a6; margin-bottom: 1rem; }\n"
        ".ad-book > :last-child { margin-bottom: 0; }\n"
    )
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write(css)

    print(f"wrote {JS_OUT} ({len(topics)} topics, {len(js)//1024} KB)")
    print(f"wrote {CSS_OUT} ({len(css)//1024} KB)")


if __name__ == "__main__":
    build()
